-- ============================================================
-- VoteCapsule™ — Migration 165: Campaign Media Enhancements
-- Adds missing columns to campaign_media required by the
-- Media Upload module (Task 1) and Lambda processor (Task 1):
--
--   media_type     VARCHAR(30)  — category of asset (poster, logo, etc.)
--   scan_status    VARCHAR(20)  — ClamAV / virus scan result
--   exif_data      JSONB        — EXIF metadata extracted by Lambda
--   preview_key    VARCHAR(500) — S3 key for 800px preview (from Lambda)
--   public_key     VARCHAR(500) — S3 key in votecapsule-public-assets after publish
--
-- Safe: uses ADD COLUMN IF NOT EXISTS throughout
-- ============================================================

BEGIN;

-- ── 1. media_type ────────────────────────────────────────────
-- Classifies the asset: campaign_photo, candidate_portrait,
-- party_logo, candidate_symbol, tshirt_design, cap_design,
-- banner_design, poster_design, ai_generated, brand_logo,
-- design_artwork, evidence_delivery, evidence_installation,
-- evidence_event, other
ALTER TABLE campaign_media
  ADD COLUMN IF NOT EXISTS media_type VARCHAR(30);

-- Index for fast filtering by type (GET /media?media_type=...)
CREATE INDEX IF NOT EXISTS idx_cm_media_type ON campaign_media(media_type);

-- ── 2. scan_status ───────────────────────────────────────────
-- Set by the campaign-media-processor Lambda after ClamAV scan.
-- Values: pending | clean | infected | skipped
ALTER TABLE campaign_media
  ADD COLUMN IF NOT EXISTS scan_status VARCHAR(20) NOT NULL DEFAULT 'pending';

-- ── 3. exif_data ─────────────────────────────────────────────
-- JSONB blob populated by the Lambda: GPS coords, camera model,
-- ISO, focal length, shot datetime, colour space, etc.
ALTER TABLE campaign_media
  ADD COLUMN IF NOT EXISTS exif_data JSONB;

-- ── 4. preview_key ───────────────────────────────────────────
-- S3 key for the 800px preview image generated by the Lambda.
-- thumbnail_key (300px) already exists from migration 135.
ALTER TABLE campaign_media
  ADD COLUMN IF NOT EXISTS preview_key VARCHAR(500);

-- ── 5. public_key ────────────────────────────────────────────
-- S3 key in votecapsule-public-assets after POST /media/:id/publish.
-- Null until explicitly published. Only party_logo,
-- candidate_portrait, candidate_symbol get published.
ALTER TABLE campaign_media
  ADD COLUMN IF NOT EXISTS public_key VARCHAR(500);

-- ── 6. Record this migration ─────────────────────────────────
INSERT INTO schema_migrations (filename, executed_at)
VALUES ('165_campaign_media_enhancements.sql', NOW())
ON CONFLICT DO NOTHING;

COMMIT;
