- name: AWS Sustainability Scanner GitHub Action
  # You may pin to the exact commit or the version.
  # uses: aws-actions/sustainability-scanner@d6067411fc5290a836e3ebcf388c746d83cf0e9f
  uses: aws-actions/sustainability-scanner@v1
  with:
    # File path of the CloudFormation template to be scanned
    file: # optional
    # Directory path with CloudFormation files to be scanned
    directory: # optional, default is .
    # CDK stack name to be scanned
    stack_name: # optional
    # File path to extend set of rules
    rules_file: # optional
